// swift-tools-version: 6.4
// Requires Xcode 27+. A floor, not a feature: the Swift 6 language mode below is identical at 6.0, and nothing here
// uses a 6.1–6.4 API. It is set deliberately to keep the package on a current toolchain.
import PackageDescription

let package = Package(
    name: "pdfx_lite",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "pdfx-lite", targets: ["pdfx_lite"]),
    ],
    // Not a third-party dependency: `FlutterFramework` is generated by the Flutter tool next to this package at build
    // time. Flutter wants an SPM plugin to declare it explicitly, and refuses to build the example app without it.
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .target(
            name: "pdfx_lite",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
            ],
            path: "Sources/pdfx_lite",
            swiftSettings: [
                // Strict concurrency. Shared state (the document/page repositories, the texture map) is reached from
                // both the platform thread and the render queue, so it is lock-guarded rather than actor-isolated.
                .swiftLanguageMode(.v6),
                // Async funcs run on the caller's executor unless marked @concurrent. Load-bearing here, not
                // cosmetic: pigeon's `PdfxApi` requirements are non-isolated `async`, and its message classes are
                // not Sendable. Without this, the implementations would either hop to the global pool (racing the
                // texture map against the platform thread) or, if isolated to fix that, fail to compile —
                // a non-Sendable parameter cannot be sent into an isolated witness of a non-isolated requirement.
                // Caller-executor semantics sidestep both: nothing crosses an isolation boundary at all, and
                // pigeon calls every handler from `Task { @MainActor in … }`, i.e. the platform thread.
                .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
            ]
        ),
    ]
)
