// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// No `password` field: only the web renderer ever honoured one. Android and
/// iOS never read it, so an encrypted document fails to open regardless.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OpenDataMessage: Hashable, CustomStringConvertible {
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenDataMessage? {
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])

    return OpenDataMessage(
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      data
    ]
  }
  static func == (lhs: OpenDataMessage, rhs: OpenDataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenDataMessage")
    PigeonPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "OpenDataMessage(data: \(String(describing: data)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenPathMessage: Hashable, CustomStringConvertible {
  var path: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenPathMessage? {
    let path: String? = nilOrValue(pigeonVar_list[0])

    return OpenPathMessage(
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      path
    ]
  }
  static func == (lhs: OpenPathMessage, rhs: OpenPathMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenPathMessage")
    PigeonPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "OpenPathMessage(path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenReply: Hashable, CustomStringConvertible {
  var id: String? = nil
  var pagesCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenReply? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let pagesCount: Int64? = nilOrValue(pigeonVar_list[1])

    return OpenReply(
      id: id,
      pagesCount: pagesCount
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      pagesCount,
    ]
  }
  static func == (lhs: OpenReply, rhs: OpenReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.id, rhs.id) && PigeonPigeonInternal.deepEquals(lhs.pagesCount, rhs.pagesCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenReply")
    PigeonPigeonInternal.deepHash(value: id, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: pagesCount, hasher: &hasher)
  }

  public var description: String {
    return "OpenReply(id: \(String(describing: id)), pagesCount: \(String(describing: pagesCount)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IdMessage: Hashable, CustomStringConvertible {
  var id: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdMessage? {
    let id: String? = nilOrValue(pigeonVar_list[0])

    return IdMessage(
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      id
    ]
  }
  static func == (lhs: IdMessage, rhs: IdMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IdMessage")
    PigeonPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "IdMessage(id: \(String(describing: id)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetPageMessage: Hashable, CustomStringConvertible {
  var documentId: String? = nil
  var pageNumber: Int64? = nil
  var autoCloseAndroid: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetPageMessage? {
    let documentId: String? = nilOrValue(pigeonVar_list[0])
    let pageNumber: Int64? = nilOrValue(pigeonVar_list[1])
    let autoCloseAndroid: Bool? = nilOrValue(pigeonVar_list[2])

    return GetPageMessage(
      documentId: documentId,
      pageNumber: pageNumber,
      autoCloseAndroid: autoCloseAndroid
    )
  }
  func toList() -> [Any?] {
    return [
      documentId,
      pageNumber,
      autoCloseAndroid,
    ]
  }
  static func == (lhs: GetPageMessage, rhs: GetPageMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.documentId, rhs.documentId) && PigeonPigeonInternal.deepEquals(lhs.pageNumber, rhs.pageNumber) && PigeonPigeonInternal.deepEquals(lhs.autoCloseAndroid, rhs.autoCloseAndroid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetPageMessage")
    PigeonPigeonInternal.deepHash(value: documentId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: pageNumber, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: autoCloseAndroid, hasher: &hasher)
  }

  public var description: String {
    return "GetPageMessage(documentId: \(String(describing: documentId)), pageNumber: \(String(describing: pageNumber)), autoCloseAndroid: \(String(describing: autoCloseAndroid)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetPageReply: Hashable, CustomStringConvertible {
  var id: String? = nil
  var width: Double? = nil
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetPageReply? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let width: Double? = nilOrValue(pigeonVar_list[1])
    let height: Double? = nilOrValue(pigeonVar_list[2])

    return GetPageReply(
      id: id,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      width,
      height,
    ]
  }
  static func == (lhs: GetPageReply, rhs: GetPageReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.id, rhs.id) && PigeonPigeonInternal.deepEquals(lhs.width, rhs.width) && PigeonPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetPageReply")
    PigeonPigeonInternal.deepHash(value: id, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: width, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "GetPageReply(id: \(String(describing: id)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RenderPageMessage: Hashable, CustomStringConvertible {
  var pageId: String? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var format: Int64? = nil
  var backgroundColor: String? = nil
  var crop: Bool? = nil
  var cropX: Int64? = nil
  var cropY: Int64? = nil
  var cropHeight: Int64? = nil
  var cropWidth: Int64? = nil
  var quality: Int64? = nil
  var forPrint: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RenderPageMessage? {
    let pageId: String? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let height: Int64? = nilOrValue(pigeonVar_list[2])
    let format: Int64? = nilOrValue(pigeonVar_list[3])
    let backgroundColor: String? = nilOrValue(pigeonVar_list[4])
    let crop: Bool? = nilOrValue(pigeonVar_list[5])
    let cropX: Int64? = nilOrValue(pigeonVar_list[6])
    let cropY: Int64? = nilOrValue(pigeonVar_list[7])
    let cropHeight: Int64? = nilOrValue(pigeonVar_list[8])
    let cropWidth: Int64? = nilOrValue(pigeonVar_list[9])
    let quality: Int64? = nilOrValue(pigeonVar_list[10])
    let forPrint: Bool? = nilOrValue(pigeonVar_list[11])

    return RenderPageMessage(
      pageId: pageId,
      width: width,
      height: height,
      format: format,
      backgroundColor: backgroundColor,
      crop: crop,
      cropX: cropX,
      cropY: cropY,
      cropHeight: cropHeight,
      cropWidth: cropWidth,
      quality: quality,
      forPrint: forPrint
    )
  }
  func toList() -> [Any?] {
    return [
      pageId,
      width,
      height,
      format,
      backgroundColor,
      crop,
      cropX,
      cropY,
      cropHeight,
      cropWidth,
      quality,
      forPrint,
    ]
  }
  static func == (lhs: RenderPageMessage, rhs: RenderPageMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.pageId, rhs.pageId) && PigeonPigeonInternal.deepEquals(lhs.width, rhs.width) && PigeonPigeonInternal.deepEquals(lhs.height, rhs.height) && PigeonPigeonInternal.deepEquals(lhs.format, rhs.format) && PigeonPigeonInternal.deepEquals(lhs.backgroundColor, rhs.backgroundColor) && PigeonPigeonInternal.deepEquals(lhs.crop, rhs.crop) && PigeonPigeonInternal.deepEquals(lhs.cropX, rhs.cropX) && PigeonPigeonInternal.deepEquals(lhs.cropY, rhs.cropY) && PigeonPigeonInternal.deepEquals(lhs.cropHeight, rhs.cropHeight) && PigeonPigeonInternal.deepEquals(lhs.cropWidth, rhs.cropWidth) && PigeonPigeonInternal.deepEquals(lhs.quality, rhs.quality) && PigeonPigeonInternal.deepEquals(lhs.forPrint, rhs.forPrint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RenderPageMessage")
    PigeonPigeonInternal.deepHash(value: pageId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: width, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: height, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: format, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: backgroundColor, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: crop, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: cropX, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: cropY, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: cropHeight, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: cropWidth, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: quality, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: forPrint, hasher: &hasher)
  }

  public var description: String {
    return "RenderPageMessage(pageId: \(String(describing: pageId)), width: \(String(describing: width)), height: \(String(describing: height)), format: \(String(describing: format)), backgroundColor: \(String(describing: backgroundColor)), crop: \(String(describing: crop)), cropX: \(String(describing: cropX)), cropY: \(String(describing: cropY)), cropHeight: \(String(describing: cropHeight)), cropWidth: \(String(describing: cropWidth)), quality: \(String(describing: quality)), forPrint: \(String(describing: forPrint)))"
  }
}

/// Android and iOS both render to a temp file; the in-memory `data` field this
/// carried upstream served the web/windows renderers and is gone with them.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RenderPageReply: Hashable, CustomStringConvertible {
  var width: Int64? = nil
  var height: Int64? = nil
  var path: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RenderPageReply? {
    let width: Int64? = nilOrValue(pigeonVar_list[0])
    let height: Int64? = nilOrValue(pigeonVar_list[1])
    let path: String? = nilOrValue(pigeonVar_list[2])

    return RenderPageReply(
      width: width,
      height: height,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      path,
    ]
  }
  static func == (lhs: RenderPageReply, rhs: RenderPageReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.width, rhs.width) && PigeonPigeonInternal.deepEquals(lhs.height, rhs.height) && PigeonPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RenderPageReply")
    PigeonPigeonInternal.deepHash(value: width, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: height, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "RenderPageReply(width: \(String(describing: width)), height: \(String(describing: height)), path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegisterTextureReply: Hashable, CustomStringConvertible {
  var id: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterTextureReply? {
    let id: Int64? = nilOrValue(pigeonVar_list[0])

    return RegisterTextureReply(
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      id
    ]
  }
  static func == (lhs: RegisterTextureReply, rhs: RegisterTextureReply) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterTextureReply")
    PigeonPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "RegisterTextureReply(id: \(String(describing: id)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdateTextureMessage: Hashable, CustomStringConvertible {
  var documentId: String? = nil
  var pageNumber: Int64? = nil
  var pageId: String? = nil
  var textureId: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var backgroundColor: String? = nil
  var sourceX: Int64? = nil
  var sourceY: Int64? = nil
  var destinationX: Int64? = nil
  var destinationY: Int64? = nil
  var fullWidth: Double? = nil
  var fullHeight: Double? = nil
  var textureWidth: Int64? = nil
  var textureHeight: Int64? = nil
  var allowAntiAliasing: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateTextureMessage? {
    let documentId: String? = nilOrValue(pigeonVar_list[0])
    let pageNumber: Int64? = nilOrValue(pigeonVar_list[1])
    let pageId: String? = nilOrValue(pigeonVar_list[2])
    let textureId: Int64? = nilOrValue(pigeonVar_list[3])
    let width: Int64? = nilOrValue(pigeonVar_list[4])
    let height: Int64? = nilOrValue(pigeonVar_list[5])
    let backgroundColor: String? = nilOrValue(pigeonVar_list[6])
    let sourceX: Int64? = nilOrValue(pigeonVar_list[7])
    let sourceY: Int64? = nilOrValue(pigeonVar_list[8])
    let destinationX: Int64? = nilOrValue(pigeonVar_list[9])
    let destinationY: Int64? = nilOrValue(pigeonVar_list[10])
    let fullWidth: Double? = nilOrValue(pigeonVar_list[11])
    let fullHeight: Double? = nilOrValue(pigeonVar_list[12])
    let textureWidth: Int64? = nilOrValue(pigeonVar_list[13])
    let textureHeight: Int64? = nilOrValue(pigeonVar_list[14])
    let allowAntiAliasing: Bool? = nilOrValue(pigeonVar_list[15])

    return UpdateTextureMessage(
      documentId: documentId,
      pageNumber: pageNumber,
      pageId: pageId,
      textureId: textureId,
      width: width,
      height: height,
      backgroundColor: backgroundColor,
      sourceX: sourceX,
      sourceY: sourceY,
      destinationX: destinationX,
      destinationY: destinationY,
      fullWidth: fullWidth,
      fullHeight: fullHeight,
      textureWidth: textureWidth,
      textureHeight: textureHeight,
      allowAntiAliasing: allowAntiAliasing
    )
  }
  func toList() -> [Any?] {
    return [
      documentId,
      pageNumber,
      pageId,
      textureId,
      width,
      height,
      backgroundColor,
      sourceX,
      sourceY,
      destinationX,
      destinationY,
      fullWidth,
      fullHeight,
      textureWidth,
      textureHeight,
      allowAntiAliasing,
    ]
  }
  static func == (lhs: UpdateTextureMessage, rhs: UpdateTextureMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.documentId, rhs.documentId) && PigeonPigeonInternal.deepEquals(lhs.pageNumber, rhs.pageNumber) && PigeonPigeonInternal.deepEquals(lhs.pageId, rhs.pageId) && PigeonPigeonInternal.deepEquals(lhs.textureId, rhs.textureId) && PigeonPigeonInternal.deepEquals(lhs.width, rhs.width) && PigeonPigeonInternal.deepEquals(lhs.height, rhs.height) && PigeonPigeonInternal.deepEquals(lhs.backgroundColor, rhs.backgroundColor) && PigeonPigeonInternal.deepEquals(lhs.sourceX, rhs.sourceX) && PigeonPigeonInternal.deepEquals(lhs.sourceY, rhs.sourceY) && PigeonPigeonInternal.deepEquals(lhs.destinationX, rhs.destinationX) && PigeonPigeonInternal.deepEquals(lhs.destinationY, rhs.destinationY) && PigeonPigeonInternal.deepEquals(lhs.fullWidth, rhs.fullWidth) && PigeonPigeonInternal.deepEquals(lhs.fullHeight, rhs.fullHeight) && PigeonPigeonInternal.deepEquals(lhs.textureWidth, rhs.textureWidth) && PigeonPigeonInternal.deepEquals(lhs.textureHeight, rhs.textureHeight) && PigeonPigeonInternal.deepEquals(lhs.allowAntiAliasing, rhs.allowAntiAliasing)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdateTextureMessage")
    PigeonPigeonInternal.deepHash(value: documentId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: pageNumber, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: pageId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: textureId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: width, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: height, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: backgroundColor, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: sourceX, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: sourceY, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: destinationX, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: destinationY, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: fullWidth, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: fullHeight, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: textureWidth, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: textureHeight, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: allowAntiAliasing, hasher: &hasher)
  }

  public var description: String {
    return "UpdateTextureMessage(documentId: \(String(describing: documentId)), pageNumber: \(String(describing: pageNumber)), pageId: \(String(describing: pageId)), textureId: \(String(describing: textureId)), width: \(String(describing: width)), height: \(String(describing: height)), backgroundColor: \(String(describing: backgroundColor)), sourceX: \(String(describing: sourceX)), sourceY: \(String(describing: sourceY)), destinationX: \(String(describing: destinationX)), destinationY: \(String(describing: destinationY)), fullWidth: \(String(describing: fullWidth)), fullHeight: \(String(describing: fullHeight)), textureWidth: \(String(describing: textureWidth)), textureHeight: \(String(describing: textureHeight)), allowAntiAliasing: \(String(describing: allowAntiAliasing)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ResizeTextureMessage: Hashable, CustomStringConvertible {
  var textureId: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ResizeTextureMessage? {
    let textureId: Int64? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let height: Int64? = nilOrValue(pigeonVar_list[2])

    return ResizeTextureMessage(
      textureId: textureId,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      width,
      height,
    ]
  }
  static func == (lhs: ResizeTextureMessage, rhs: ResizeTextureMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.textureId, rhs.textureId) && PigeonPigeonInternal.deepEquals(lhs.width, rhs.width) && PigeonPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ResizeTextureMessage")
    PigeonPigeonInternal.deepHash(value: textureId, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: width, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "ResizeTextureMessage(textureId: \(String(describing: textureId)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UnregisterTextureMessage: Hashable, CustomStringConvertible {
  var id: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UnregisterTextureMessage? {
    let id: Int64? = nilOrValue(pigeonVar_list[0])

    return UnregisterTextureMessage(
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      id
    ]
  }
  static func == (lhs: UnregisterTextureMessage, rhs: UnregisterTextureMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UnregisterTextureMessage")
    PigeonPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "UnregisterTextureMessage(id: \(String(describing: id)))"
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return OpenDataMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return OpenPathMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return OpenReply.fromList(self.readValue() as! [Any?])
    case 132:
      return IdMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return GetPageMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return GetPageReply.fromList(self.readValue() as! [Any?])
    case 135:
      return RenderPageMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return RenderPageReply.fromList(self.readValue() as! [Any?])
    case 137:
      return RegisterTextureReply.fromList(self.readValue() as! [Any?])
    case 138:
      return UpdateTextureMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return ResizeTextureMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return UnregisterTextureMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OpenDataMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? OpenPathMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? OpenReply {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? IdMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GetPageMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? GetPageReply {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RenderPageMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? RenderPageReply {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterTextureReply {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateTextureMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ResizeTextureMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? UnregisterTextureMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfxApi {
  func openDocumentData(message: OpenDataMessage, completion: @escaping (Result<OpenReply, Error>) -> Void)
  func openDocumentFile(message: OpenPathMessage, completion: @escaping (Result<OpenReply, Error>) -> Void)
  func openDocumentAsset(message: OpenPathMessage, completion: @escaping (Result<OpenReply, Error>) -> Void)
  func closeDocument(message: IdMessage) throws
  func getPage(message: GetPageMessage, completion: @escaping (Result<GetPageReply, Error>) -> Void)
  func renderPage(message: RenderPageMessage, completion: @escaping (Result<RenderPageReply, Error>) -> Void)
  func closePage(message: IdMessage) throws
  func registerTexture() throws -> RegisterTextureReply
  func updateTexture(message: UpdateTextureMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func resizeTexture(message: ResizeTextureMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func unregisterTexture(message: UnregisterTextureMessage) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfxApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `PdfxApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfxApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openDocumentDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openDocumentDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! OpenDataMessage
        api.openDocumentData(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openDocumentDataChannel.setMessageHandler(nil)
    }
    let openDocumentFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openDocumentFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! OpenPathMessage
        api.openDocumentFile(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openDocumentFileChannel.setMessageHandler(nil)
    }
    let openDocumentAssetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentAsset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openDocumentAssetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! OpenPathMessage
        api.openDocumentAsset(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openDocumentAssetChannel.setMessageHandler(nil)
    }
    let closeDocumentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.closeDocument\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeDocumentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! IdMessage
        do {
          try api.closeDocument(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeDocumentChannel.setMessageHandler(nil)
    }
    let getPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.getPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! GetPageMessage
        api.getPage(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPageChannel.setMessageHandler(nil)
    }
    let renderPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.renderPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! RenderPageMessage
        api.renderPage(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      renderPageChannel.setMessageHandler(nil)
    }
    let closePageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.closePage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closePageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! IdMessage
        do {
          try api.closePage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closePageChannel.setMessageHandler(nil)
    }
    let registerTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.registerTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerTextureChannel.setMessageHandler { _, reply in
        do {
          let result = try api.registerTexture()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerTextureChannel.setMessageHandler(nil)
    }
    let updateTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.updateTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! UpdateTextureMessage
        api.updateTexture(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateTextureChannel.setMessageHandler(nil)
    }
    let resizeTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.resizeTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resizeTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! ResizeTextureMessage
        api.resizeTexture(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resizeTextureChannel.setMessageHandler(nil)
    }
    let unregisterTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdfx_lite.PdfxApi.unregisterTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! UnregisterTextureMessage
        do {
          try api.unregisterTexture(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unregisterTextureChannel.setMessageHandler(nil)
    }
  }
}
