// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.scer.pdfx

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * [password] unlocks an encrypted document. iOS honours it on every version we
 * support; Android needs API 35. See `PdfxApi.isPasswordSupported`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OpenDataMessage (
  val data: ByteArray? = null,
  val password: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenDataMessage {
      val data = pigeonVar_list[0] as ByteArray?
      val password = pigeonVar_list[1] as String?
      return OpenDataMessage(data, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenDataMessage
    return PigeonPigeonUtils.deepEquals(this.data, other.data) && PigeonPigeonUtils.deepEquals(this.password, other.password)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.data)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.password)
    return result
  }
  override fun toString(): String {
    return "OpenDataMessage(data=${data?.contentToString()}, password=$password)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenPathMessage (
  val path: String? = null,
  val password: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenPathMessage {
      val path = pigeonVar_list[0] as String?
      val password = pigeonVar_list[1] as String?
      return OpenPathMessage(path, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenPathMessage
    return PigeonPigeonUtils.deepEquals(this.path, other.path) && PigeonPigeonUtils.deepEquals(this.password, other.password)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.path)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.password)
    return result
  }
  override fun toString(): String {
    return "OpenPathMessage(path=$path, password=$password)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenReply (
  val id: String? = null,
  val pagesCount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenReply {
      val id = pigeonVar_list[0] as String?
      val pagesCount = pigeonVar_list[1] as Long?
      return OpenReply(id, pagesCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      pagesCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenReply
    return PigeonPigeonUtils.deepEquals(this.id, other.id) && PigeonPigeonUtils.deepEquals(this.pagesCount, other.pagesCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.pagesCount)
    return result
  }
  override fun toString(): String {
    return "OpenReply(id=$id, pagesCount=$pagesCount)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IdMessage (
  val id: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IdMessage {
      val id = pigeonVar_list[0] as String?
      return IdMessage(id)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IdMessage
    return PigeonPigeonUtils.deepEquals(this.id, other.id)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    return result
  }
  override fun toString(): String {
    return "IdMessage(id=$id)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetPageMessage (
  val documentId: String? = null,
  val pageNumber: Long? = null,
  val autoCloseAndroid: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetPageMessage {
      val documentId = pigeonVar_list[0] as String?
      val pageNumber = pigeonVar_list[1] as Long?
      val autoCloseAndroid = pigeonVar_list[2] as Boolean?
      return GetPageMessage(documentId, pageNumber, autoCloseAndroid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      documentId,
      pageNumber,
      autoCloseAndroid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetPageMessage
    return PigeonPigeonUtils.deepEquals(this.documentId, other.documentId) && PigeonPigeonUtils.deepEquals(this.pageNumber, other.pageNumber) && PigeonPigeonUtils.deepEquals(this.autoCloseAndroid, other.autoCloseAndroid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.documentId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.pageNumber)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.autoCloseAndroid)
    return result
  }
  override fun toString(): String {
    return "GetPageMessage(documentId=$documentId, pageNumber=$pageNumber, autoCloseAndroid=$autoCloseAndroid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetPageReply (
  val id: String? = null,
  val width: Double? = null,
  val height: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetPageReply {
      val id = pigeonVar_list[0] as String?
      val width = pigeonVar_list[1] as Double?
      val height = pigeonVar_list[2] as Double?
      return GetPageReply(id, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetPageReply
    return PigeonPigeonUtils.deepEquals(this.id, other.id) && PigeonPigeonUtils.deepEquals(this.width, other.width) && PigeonPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.width)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "GetPageReply(id=$id, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RenderPageMessage (
  val pageId: String? = null,
  val width: Long? = null,
  val height: Long? = null,
  val format: Long? = null,
  val backgroundColor: String? = null,
  val crop: Boolean? = null,
  val cropX: Long? = null,
  val cropY: Long? = null,
  val cropHeight: Long? = null,
  val cropWidth: Long? = null,
  val quality: Long? = null,
  val forPrint: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RenderPageMessage {
      val pageId = pigeonVar_list[0] as String?
      val width = pigeonVar_list[1] as Long?
      val height = pigeonVar_list[2] as Long?
      val format = pigeonVar_list[3] as Long?
      val backgroundColor = pigeonVar_list[4] as String?
      val crop = pigeonVar_list[5] as Boolean?
      val cropX = pigeonVar_list[6] as Long?
      val cropY = pigeonVar_list[7] as Long?
      val cropHeight = pigeonVar_list[8] as Long?
      val cropWidth = pigeonVar_list[9] as Long?
      val quality = pigeonVar_list[10] as Long?
      val forPrint = pigeonVar_list[11] as Boolean?
      return RenderPageMessage(pageId, width, height, format, backgroundColor, crop, cropX, cropY, cropHeight, cropWidth, quality, forPrint)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pageId,
      width,
      height,
      format,
      backgroundColor,
      crop,
      cropX,
      cropY,
      cropHeight,
      cropWidth,
      quality,
      forPrint,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RenderPageMessage
    return PigeonPigeonUtils.deepEquals(this.pageId, other.pageId) && PigeonPigeonUtils.deepEquals(this.width, other.width) && PigeonPigeonUtils.deepEquals(this.height, other.height) && PigeonPigeonUtils.deepEquals(this.format, other.format) && PigeonPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && PigeonPigeonUtils.deepEquals(this.crop, other.crop) && PigeonPigeonUtils.deepEquals(this.cropX, other.cropX) && PigeonPigeonUtils.deepEquals(this.cropY, other.cropY) && PigeonPigeonUtils.deepEquals(this.cropHeight, other.cropHeight) && PigeonPigeonUtils.deepEquals(this.cropWidth, other.cropWidth) && PigeonPigeonUtils.deepEquals(this.quality, other.quality) && PigeonPigeonUtils.deepEquals(this.forPrint, other.forPrint)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.pageId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.width)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.height)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.format)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.crop)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.cropX)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.cropY)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.cropHeight)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.cropWidth)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.quality)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.forPrint)
    return result
  }
  override fun toString(): String {
    return "RenderPageMessage(pageId=$pageId, width=$width, height=$height, format=$format, backgroundColor=$backgroundColor, crop=$crop, cropX=$cropX, cropY=$cropY, cropHeight=$cropHeight, cropWidth=$cropWidth, quality=$quality, forPrint=$forPrint)"
  }
}

/**
 * Android and iOS both render to a temp file; the in-memory `data` field this
 * carried upstream served the web/windows renderers and is gone with them.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RenderPageReply (
  val width: Long? = null,
  val height: Long? = null,
  val path: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RenderPageReply {
      val width = pigeonVar_list[0] as Long?
      val height = pigeonVar_list[1] as Long?
      val path = pigeonVar_list[2] as String?
      return RenderPageReply(width, height, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RenderPageReply
    return PigeonPigeonUtils.deepEquals(this.width, other.width) && PigeonPigeonUtils.deepEquals(this.height, other.height) && PigeonPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.width)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.height)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "RenderPageReply(width=$width, height=$height, path=$path)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegisterTextureReply (
  val id: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterTextureReply {
      val id = pigeonVar_list[0] as Long?
      return RegisterTextureReply(id)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterTextureReply
    return PigeonPigeonUtils.deepEquals(this.id, other.id)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    return result
  }
  override fun toString(): String {
    return "RegisterTextureReply(id=$id)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdateTextureMessage (
  val documentId: String? = null,
  val pageNumber: Long? = null,
  val pageId: String? = null,
  val textureId: Long? = null,
  val width: Long? = null,
  val height: Long? = null,
  val backgroundColor: String? = null,
  val sourceX: Long? = null,
  val sourceY: Long? = null,
  val destinationX: Long? = null,
  val destinationY: Long? = null,
  val fullWidth: Double? = null,
  val fullHeight: Double? = null,
  val textureWidth: Long? = null,
  val textureHeight: Long? = null,
  val allowAntiAliasing: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdateTextureMessage {
      val documentId = pigeonVar_list[0] as String?
      val pageNumber = pigeonVar_list[1] as Long?
      val pageId = pigeonVar_list[2] as String?
      val textureId = pigeonVar_list[3] as Long?
      val width = pigeonVar_list[4] as Long?
      val height = pigeonVar_list[5] as Long?
      val backgroundColor = pigeonVar_list[6] as String?
      val sourceX = pigeonVar_list[7] as Long?
      val sourceY = pigeonVar_list[8] as Long?
      val destinationX = pigeonVar_list[9] as Long?
      val destinationY = pigeonVar_list[10] as Long?
      val fullWidth = pigeonVar_list[11] as Double?
      val fullHeight = pigeonVar_list[12] as Double?
      val textureWidth = pigeonVar_list[13] as Long?
      val textureHeight = pigeonVar_list[14] as Long?
      val allowAntiAliasing = pigeonVar_list[15] as Boolean?
      return UpdateTextureMessage(documentId, pageNumber, pageId, textureId, width, height, backgroundColor, sourceX, sourceY, destinationX, destinationY, fullWidth, fullHeight, textureWidth, textureHeight, allowAntiAliasing)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      documentId,
      pageNumber,
      pageId,
      textureId,
      width,
      height,
      backgroundColor,
      sourceX,
      sourceY,
      destinationX,
      destinationY,
      fullWidth,
      fullHeight,
      textureWidth,
      textureHeight,
      allowAntiAliasing,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdateTextureMessage
    return PigeonPigeonUtils.deepEquals(this.documentId, other.documentId) && PigeonPigeonUtils.deepEquals(this.pageNumber, other.pageNumber) && PigeonPigeonUtils.deepEquals(this.pageId, other.pageId) && PigeonPigeonUtils.deepEquals(this.textureId, other.textureId) && PigeonPigeonUtils.deepEquals(this.width, other.width) && PigeonPigeonUtils.deepEquals(this.height, other.height) && PigeonPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && PigeonPigeonUtils.deepEquals(this.sourceX, other.sourceX) && PigeonPigeonUtils.deepEquals(this.sourceY, other.sourceY) && PigeonPigeonUtils.deepEquals(this.destinationX, other.destinationX) && PigeonPigeonUtils.deepEquals(this.destinationY, other.destinationY) && PigeonPigeonUtils.deepEquals(this.fullWidth, other.fullWidth) && PigeonPigeonUtils.deepEquals(this.fullHeight, other.fullHeight) && PigeonPigeonUtils.deepEquals(this.textureWidth, other.textureWidth) && PigeonPigeonUtils.deepEquals(this.textureHeight, other.textureHeight) && PigeonPigeonUtils.deepEquals(this.allowAntiAliasing, other.allowAntiAliasing)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.documentId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.pageNumber)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.pageId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.textureId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.width)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.height)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.sourceX)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.sourceY)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.destinationX)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.destinationY)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.fullWidth)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.fullHeight)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.textureWidth)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.textureHeight)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.allowAntiAliasing)
    return result
  }
  override fun toString(): String {
    return "UpdateTextureMessage(documentId=$documentId, pageNumber=$pageNumber, pageId=$pageId, textureId=$textureId, width=$width, height=$height, backgroundColor=$backgroundColor, sourceX=$sourceX, sourceY=$sourceY, destinationX=$destinationX, destinationY=$destinationY, fullWidth=$fullWidth, fullHeight=$fullHeight, textureWidth=$textureWidth, textureHeight=$textureHeight, allowAntiAliasing=$allowAntiAliasing)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ResizeTextureMessage (
  val textureId: Long? = null,
  val width: Long? = null,
  val height: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ResizeTextureMessage {
      val textureId = pigeonVar_list[0] as Long?
      val width = pigeonVar_list[1] as Long?
      val height = pigeonVar_list[2] as Long?
      return ResizeTextureMessage(textureId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ResizeTextureMessage
    return PigeonPigeonUtils.deepEquals(this.textureId, other.textureId) && PigeonPigeonUtils.deepEquals(this.width, other.width) && PigeonPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.textureId)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.width)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "ResizeTextureMessage(textureId=$textureId, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UnregisterTextureMessage (
  val id: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UnregisterTextureMessage {
      val id = pigeonVar_list[0] as Long?
      return UnregisterTextureMessage(id)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UnregisterTextureMessage
    return PigeonPigeonUtils.deepEquals(this.id, other.id)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.id)
    return result
  }
  override fun toString(): String {
    return "UnregisterTextureMessage(id=$id)"
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenDataMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenPathMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenReply.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IdMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetPageMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetPageReply.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RenderPageMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RenderPageReply.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterTextureReply.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdateTextureMessage.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResizeTextureMessage.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UnregisterTextureMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OpenDataMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is OpenPathMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OpenReply -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is IdMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is GetPageMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is GetPageReply -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RenderPageMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is RenderPageReply -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is RegisterTextureReply -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is UpdateTextureMessage -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ResizeTextureMessage -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is UnregisterTextureMessage -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PdfxApi {
  /**
   * Whether this device can open an encrypted PDF at all — always true on iOS,
   * but only Android 15 (API 35) upwards. Passing a `password` on a device that
   * says false fails with `PDF_PASSWORD_UNSUPPORTED` rather than being ignored.
   */
  fun isPasswordSupported(): Boolean
  fun openDocumentData(message: OpenDataMessage, callback: (Result<OpenReply>) -> Unit)
  fun openDocumentFile(message: OpenPathMessage, callback: (Result<OpenReply>) -> Unit)
  fun openDocumentAsset(message: OpenPathMessage, callback: (Result<OpenReply>) -> Unit)
  fun closeDocument(message: IdMessage)
  fun getPage(message: GetPageMessage, callback: (Result<GetPageReply>) -> Unit)
  fun renderPage(message: RenderPageMessage, callback: (Result<RenderPageReply>) -> Unit)
  fun closePage(message: IdMessage)
  fun registerTexture(): RegisterTextureReply
  fun updateTexture(message: UpdateTextureMessage, callback: (Result<Unit>) -> Unit)
  fun resizeTexture(message: ResizeTextureMessage, callback: (Result<Unit>) -> Unit)
  fun unregisterTexture(message: UnregisterTextureMessage)

  companion object {
    /** The codec used by PdfxApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `PdfxApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PdfxApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.isPasswordSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isPasswordSupported())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as OpenDataMessage
            api.openDocumentData(messageArg) { result: Result<OpenReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as OpenPathMessage
            api.openDocumentFile(messageArg) { result: Result<OpenReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentAsset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as OpenPathMessage
            api.openDocumentAsset(messageArg) { result: Result<OpenReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.closeDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as IdMessage
            val wrapped: List<Any?> = try {
              api.closeDocument(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.getPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as GetPageMessage
            api.getPage(messageArg) { result: Result<GetPageReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.renderPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as RenderPageMessage
            api.renderPage(messageArg) { result: Result<RenderPageReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.closePage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as IdMessage
            val wrapped: List<Any?> = try {
              api.closePage(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.registerTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.registerTexture())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.updateTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as UpdateTextureMessage
            api.updateTexture(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.resizeTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as ResizeTextureMessage
            api.resizeTexture(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(PigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdfx_lite.PdfxApi.unregisterTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as UnregisterTextureMessage
            val wrapped: List<Any?> = try {
              api.unregisterTexture(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
