// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// No `password` field: only the web renderer ever honoured one. Android and
/// iOS never read it, so an encrypted document fails to open regardless.
class OpenDataMessage {
  OpenDataMessage({
    this.data,
  });

  Uint8List? data;

  List<Object?> _toList() {
    return <Object?>[
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static OpenDataMessage decode(Object result) {
    result as List<Object?>;
    return OpenDataMessage(
      data: result[0] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenDataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OpenDataMessage(data: $data)';
  }
}

class OpenPathMessage {
  OpenPathMessage({
    this.path,
  });

  String? path;

  List<Object?> _toList() {
    return <Object?>[
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static OpenPathMessage decode(Object result) {
    result as List<Object?>;
    return OpenPathMessage(
      path: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenPathMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OpenPathMessage(path: $path)';
  }
}

class OpenReply {
  OpenReply({
    this.id,
    this.pagesCount,
  });

  String? id;

  int? pagesCount;

  List<Object?> _toList() {
    return <Object?>[
      id,
      pagesCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static OpenReply decode(Object result) {
    result as List<Object?>;
    return OpenReply(
      id: result[0] as String?,
      pagesCount: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpenReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(pagesCount, other.pagesCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OpenReply(id: $id, pagesCount: $pagesCount)';
  }
}

class IdMessage {
  IdMessage({
    this.id,
  });

  String? id;

  List<Object?> _toList() {
    return <Object?>[
      id,
    ];
  }

  Object encode() {
    return _toList();  }

  static IdMessage decode(Object result) {
    result as List<Object?>;
    return IdMessage(
      id: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IdMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'IdMessage(id: $id)';
  }
}

class GetPageMessage {
  GetPageMessage({
    this.documentId,
    this.pageNumber,
    this.autoCloseAndroid,
  });

  String? documentId;

  int? pageNumber;

  bool? autoCloseAndroid;

  List<Object?> _toList() {
    return <Object?>[
      documentId,
      pageNumber,
      autoCloseAndroid,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetPageMessage decode(Object result) {
    result as List<Object?>;
    return GetPageMessage(
      documentId: result[0] as String?,
      pageNumber: result[1] as int?,
      autoCloseAndroid: result[2] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetPageMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(documentId, other.documentId) && _deepEquals(pageNumber, other.pageNumber) && _deepEquals(autoCloseAndroid, other.autoCloseAndroid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GetPageMessage(documentId: $documentId, pageNumber: $pageNumber, autoCloseAndroid: $autoCloseAndroid)';
  }
}

class GetPageReply {
  GetPageReply({
    this.id,
    this.width,
    this.height,
  });

  String? id;

  double? width;

  double? height;

  List<Object?> _toList() {
    return <Object?>[
      id,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetPageReply decode(Object result) {
    result as List<Object?>;
    return GetPageReply(
      id: result[0] as String?,
      width: result[1] as double?,
      height: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetPageReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GetPageReply(id: $id, width: $width, height: $height)';
  }
}

class RenderPageMessage {
  RenderPageMessage({
    this.pageId,
    this.width,
    this.height,
    this.format,
    this.backgroundColor,
    this.crop,
    this.cropX,
    this.cropY,
    this.cropHeight,
    this.cropWidth,
    this.quality,
    this.forPrint,
  });

  String? pageId;

  int? width;

  int? height;

  int? format;

  String? backgroundColor;

  bool? crop;

  int? cropX;

  int? cropY;

  int? cropHeight;

  int? cropWidth;

  int? quality;

  bool? forPrint;

  List<Object?> _toList() {
    return <Object?>[
      pageId,
      width,
      height,
      format,
      backgroundColor,
      crop,
      cropX,
      cropY,
      cropHeight,
      cropWidth,
      quality,
      forPrint,
    ];
  }

  Object encode() {
    return _toList();  }

  static RenderPageMessage decode(Object result) {
    result as List<Object?>;
    return RenderPageMessage(
      pageId: result[0] as String?,
      width: result[1] as int?,
      height: result[2] as int?,
      format: result[3] as int?,
      backgroundColor: result[4] as String?,
      crop: result[5] as bool?,
      cropX: result[6] as int?,
      cropY: result[7] as int?,
      cropHeight: result[8] as int?,
      cropWidth: result[9] as int?,
      quality: result[10] as int?,
      forPrint: result[11] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RenderPageMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageId, other.pageId) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(format, other.format) && _deepEquals(backgroundColor, other.backgroundColor) && _deepEquals(crop, other.crop) && _deepEquals(cropX, other.cropX) && _deepEquals(cropY, other.cropY) && _deepEquals(cropHeight, other.cropHeight) && _deepEquals(cropWidth, other.cropWidth) && _deepEquals(quality, other.quality) && _deepEquals(forPrint, other.forPrint);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RenderPageMessage(pageId: $pageId, width: $width, height: $height, format: $format, backgroundColor: $backgroundColor, crop: $crop, cropX: $cropX, cropY: $cropY, cropHeight: $cropHeight, cropWidth: $cropWidth, quality: $quality, forPrint: $forPrint)';
  }
}

/// Android and iOS both render to a temp file; the in-memory `data` field this
/// carried upstream served the web/windows renderers and is gone with them.
class RenderPageReply {
  RenderPageReply({
    this.width,
    this.height,
    this.path,
  });

  int? width;

  int? height;

  String? path;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static RenderPageReply decode(Object result) {
    result as List<Object?>;
    return RenderPageReply(
      width: result[0] as int?,
      height: result[1] as int?,
      path: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RenderPageReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RenderPageReply(width: $width, height: $height, path: $path)';
  }
}

class RegisterTextureReply {
  RegisterTextureReply({
    this.id,
  });

  int? id;

  List<Object?> _toList() {
    return <Object?>[
      id,
    ];
  }

  Object encode() {
    return _toList();  }

  static RegisterTextureReply decode(Object result) {
    result as List<Object?>;
    return RegisterTextureReply(
      id: result[0] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegisterTextureReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegisterTextureReply(id: $id)';
  }
}

class UpdateTextureMessage {
  UpdateTextureMessage({
    this.documentId,
    this.pageNumber,
    this.pageId,
    this.textureId,
    this.width,
    this.height,
    this.backgroundColor,
    this.sourceX,
    this.sourceY,
    this.destinationX,
    this.destinationY,
    this.fullWidth,
    this.fullHeight,
    this.textureWidth,
    this.textureHeight,
    this.allowAntiAliasing,
  });

  String? documentId;

  int? pageNumber;

  String? pageId;

  int? textureId;

  int? width;

  int? height;

  String? backgroundColor;

  int? sourceX;

  int? sourceY;

  int? destinationX;

  int? destinationY;

  double? fullWidth;

  double? fullHeight;

  int? textureWidth;

  int? textureHeight;

  bool? allowAntiAliasing;

  List<Object?> _toList() {
    return <Object?>[
      documentId,
      pageNumber,
      pageId,
      textureId,
      width,
      height,
      backgroundColor,
      sourceX,
      sourceY,
      destinationX,
      destinationY,
      fullWidth,
      fullHeight,
      textureWidth,
      textureHeight,
      allowAntiAliasing,
    ];
  }

  Object encode() {
    return _toList();  }

  static UpdateTextureMessage decode(Object result) {
    result as List<Object?>;
    return UpdateTextureMessage(
      documentId: result[0] as String?,
      pageNumber: result[1] as int?,
      pageId: result[2] as String?,
      textureId: result[3] as int?,
      width: result[4] as int?,
      height: result[5] as int?,
      backgroundColor: result[6] as String?,
      sourceX: result[7] as int?,
      sourceY: result[8] as int?,
      destinationX: result[9] as int?,
      destinationY: result[10] as int?,
      fullWidth: result[11] as double?,
      fullHeight: result[12] as double?,
      textureWidth: result[13] as int?,
      textureHeight: result[14] as int?,
      allowAntiAliasing: result[15] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UpdateTextureMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(documentId, other.documentId) && _deepEquals(pageNumber, other.pageNumber) && _deepEquals(pageId, other.pageId) && _deepEquals(textureId, other.textureId) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(backgroundColor, other.backgroundColor) && _deepEquals(sourceX, other.sourceX) && _deepEquals(sourceY, other.sourceY) && _deepEquals(destinationX, other.destinationX) && _deepEquals(destinationY, other.destinationY) && _deepEquals(fullWidth, other.fullWidth) && _deepEquals(fullHeight, other.fullHeight) && _deepEquals(textureWidth, other.textureWidth) && _deepEquals(textureHeight, other.textureHeight) && _deepEquals(allowAntiAliasing, other.allowAntiAliasing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UpdateTextureMessage(documentId: $documentId, pageNumber: $pageNumber, pageId: $pageId, textureId: $textureId, width: $width, height: $height, backgroundColor: $backgroundColor, sourceX: $sourceX, sourceY: $sourceY, destinationX: $destinationX, destinationY: $destinationY, fullWidth: $fullWidth, fullHeight: $fullHeight, textureWidth: $textureWidth, textureHeight: $textureHeight, allowAntiAliasing: $allowAntiAliasing)';
  }
}

class ResizeTextureMessage {
  ResizeTextureMessage({
    this.textureId,
    this.width,
    this.height,
  });

  int? textureId;

  int? width;

  int? height;

  List<Object?> _toList() {
    return <Object?>[
      textureId,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static ResizeTextureMessage decode(Object result) {
    result as List<Object?>;
    return ResizeTextureMessage(
      textureId: result[0] as int?,
      width: result[1] as int?,
      height: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResizeTextureMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ResizeTextureMessage(textureId: $textureId, width: $width, height: $height)';
  }
}

class UnregisterTextureMessage {
  UnregisterTextureMessage({
    this.id,
  });

  int? id;

  List<Object?> _toList() {
    return <Object?>[
      id,
    ];
  }

  Object encode() {
    return _toList();  }

  static UnregisterTextureMessage decode(Object result) {
    result as List<Object?>;
    return UnregisterTextureMessage(
      id: result[0] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnregisterTextureMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UnregisterTextureMessage(id: $id)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OpenDataMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is OpenPathMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is OpenReply) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is IdMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GetPageMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GetPageReply) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is RenderPageMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is RenderPageReply) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is RegisterTextureReply) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is UpdateTextureMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is ResizeTextureMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is UnregisterTextureMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return OpenDataMessage.decode(readValue(buffer)!);
      case 130:
        return OpenPathMessage.decode(readValue(buffer)!);
      case 131:
        return OpenReply.decode(readValue(buffer)!);
      case 132:
        return IdMessage.decode(readValue(buffer)!);
      case 133:
        return GetPageMessage.decode(readValue(buffer)!);
      case 134:
        return GetPageReply.decode(readValue(buffer)!);
      case 135:
        return RenderPageMessage.decode(readValue(buffer)!);
      case 136:
        return RenderPageReply.decode(readValue(buffer)!);
      case 137:
        return RegisterTextureReply.decode(readValue(buffer)!);
      case 138:
        return UpdateTextureMessage.decode(readValue(buffer)!);
      case 139:
        return ResizeTextureMessage.decode(readValue(buffer)!);
      case 140:
        return UnregisterTextureMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PdfxApi {
  /// Constructor for [PdfxApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PdfxApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<OpenReply> openDocumentData(OpenDataMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OpenReply;
  }

  Future<OpenReply> openDocumentFile(OpenPathMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OpenReply;
  }

  Future<OpenReply> openDocumentAsset(OpenPathMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.openDocumentAsset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OpenReply;
  }

  Future<void> closeDocument(IdMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.closeDocument$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<GetPageReply> getPage(GetPageMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.getPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GetPageReply;
  }

  Future<RenderPageReply> renderPage(RenderPageMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.renderPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RenderPageReply;
  }

  Future<void> closePage(IdMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.closePage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<RegisterTextureReply> registerTexture() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.registerTexture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RegisterTextureReply;
  }

  Future<void> updateTexture(UpdateTextureMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.updateTexture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> resizeTexture(ResizeTextureMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.resizeTexture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> unregisterTexture(UnregisterTextureMessage message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.pdfx_lite.PdfxApi.unregisterTexture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
